# Generated by Django 5.0.6 on 2024-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0002_customuser_is_donor_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
