# Generated by Django 5.0.6 on 2024-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0003_customuser_address_customuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
