# Generated by Django 5.0.6 on 2024-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0007_petsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsdata',
            name='name',
        ),
        migrations.AlterField(
            model_name='petsdata',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
