# Generated by Django 5.0.6 on 2024-07-02 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0007_petdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetails',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
