# Generated by Django 5.0.6 on 2024-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0008_alter_petdetails_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetails',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
