# Generated by Django 5.0.6 on 2024-07-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0009_alter_petdetails_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetails',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
