# Generated by Django 5.0.6 on 2024-07-03 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0010_alter_petdetails_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptedPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adopted', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pets_api.petdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
