# Generated by Django 5.0.6 on 2024-07-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_api', '0012_adoptionnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
